<?php

namespace JustBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{


    public function uneMethode()
    {
        $query = $this->createQueryBuilder('student_repository')
            ->addOrderBy('student_repository.dateOfBirth'. 'DESC')
            ->getQuery()
        ;
        return $query->getResult();
    }

    public function displayAge()
    {
        $data = $this->findAll();
        return $data;
    }
}

